FilmProjesi/Models/ErrorViewModel.cs
namespace FilmProjesi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FilmProjesi/Models/Film.cs
using System.ComponentModel.DataAnnotations;

namespace FilmProjesi.Models
{
    public class Film
    {
        [Key]
        public int FilmID { get; set; }
        public string FilmAd { get; set; }
        public string FilmAciklama { get; set; }
        public ICollection<Yorum> FilmYorumlar { get; set; }
        public Film()
        {
            FilmYorumlar = new List<Yorum>();
        }
    }
}

FilmProjesi/Models/FilmViewModel.cs
using FilmProjesi.Data;

namespace FilmProjesi.Models
{
    public class FilmViewModel
    {
        public Film Film;
        public List<Film> Filmler;
    }
}

FilmProjesi/Models/Yorum.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FilmProjesi.Models
{
    public class Yorum
    {
        [Key]
        public int YorumID { get; set; }

        public string YorumAciklama { get; set; }

        public DateTime YorumTarihi { get; set; } = DateTime.Now;
        public int FilmID { get; set; }
        public string YorumSahibi { get; set; }

        [ForeignKey("FilmID")]
        public Film Film { get; set; } 
    }
}

FilmProjesi/Controllers/BaseController.cs
using FilmProjesi.Data;
using FilmProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace FilmProjesi.Controllers
{
    public class BaseController : Controller
    {
        protected readonly Context _Context;

        public BaseController(Context context)
        {
            _Context = context;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var filmViewModel = new FilmViewModel();
            filmViewModel.Filmler = _Context.Filmler.ToList();
            ViewBag.FilmViewModel = filmViewModel;
            base.OnActionExecuting(context);
        }
    }
}

FilmProjesi/Controllers/FilmController.cs
using FilmProjesi.Data;
using FilmProjesi.Models;
using FilmProjesi.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FilmProjesi.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmRepository _filmRepository;

        public FilmController(IFilmRepository filmRepository)
        {
            _filmRepository = filmRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FilmEkle() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult FilmEkle(string FilmAd,string FilmAciklama)
        {
            Film film = new Film { FilmAd = FilmAd, FilmAciklama = FilmAciklama};
            _filmRepository.add(film);
            return RedirectToAction("Index","Home");
        }
    }
}

FilmProjesi/Controllers/HomeController.cs
using FilmProjesi.Data;
using FilmProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using FilmProjesi.Repos;

namespace FilmProjesi.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFilmRepository _filmRepository;
        private readonly IYorumRepository _yorumRepository;

        public HomeController(ILogger<HomeController> logger, Context context, IFilmRepository filmRepository, IYorumRepository yorumRepository)
            : base(context)
        {
            _logger = logger;
            _filmRepository = filmRepository;
            _yorumRepository = yorumRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FilmDetay(int id)
        {
            return View(_filmRepository.getById(id));
        }

        [Authorize]
        public IActionResult YorumEkle(string Yorum, int id, string username)
        {
            Film film = _filmRepository.getById(id);
            var yorum = new Yorum
            {
                YorumAciklama = Yorum,
                YorumTarihi = DateTime.Now,
                YorumSahibi = username,
                FilmID = id
            };
            film.FilmYorumlar.Add(yorum);
            _yorumRepository.add(yorum);
            return RedirectToAction("FilmDetay", new { id = id });
        }

        public IActionResult Yorumlarim(string username)
        {
            List<Yorum> tumYorumlar = _yorumRepository.getByUsername(username);
            Dictionary<string, List<Yorum>> filmYorumlar = new Dictionary<string, List<Yorum>>();
            foreach (var yorum in tumYorumlar)
            {
                Film film = _filmRepository.getById(yorum.FilmID);
                if (film != null && !string.IsNullOrEmpty(film.FilmAd))
                {
                    string filmName = film.FilmAd;
                    if (!filmYorumlar.ContainsKey(filmName))
                    {
                        filmYorumlar[filmName] = new List<Yorum>();
                    }
                    filmYorumlar[filmName].Add(yorum);
                }
            }
            return View(filmYorumlar);
        }

        public IActionResult YorumSil(int id)
        {
            _yorumRepository.sil(_yorumRepository.getById(id));
            return RedirectToAction("Index"); // yorumlarım kısmına geri dönmesi lazım orası ayarlanacak
        }

        public IActionResult YorumDuzenle(int id)
        {
            return View(_yorumRepository.getById(id));
        }

        public IActionResult Duzenle(int id, string NewYorum)
        {
            _yorumRepository.guncelle(id,NewYorum);
            return RedirectToAction("Index");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FilmProjesi/Views/Home/FilmDetay.cshtml
@model Film

<h1>Film Açıklaması</h1>
@Model.FilmAciklama

<h1>Yorumlar</h1>

@foreach(var yorum in Model.FilmYorumlar)
{
    <ul>
        <li>@yorum.YorumAciklama</li>
        <li>@yorum.YorumTarihi</li>
        <li>@yorum.YorumSahibi</li>
    </ul>
}

@if (User.Identity.IsAuthenticated)
{
    <h1>Yorum Yap</h1>
    <form method="post" action="/Home/YorumEkle">
        <input type="hidden" name="id" value="@Model.FilmID" />
        <textarea rows="4" cols="50" id="txtYorum" name="Yorum"></textarea><br />
        <input type="hidden" name="username" value="@User.Identity.Name">
        <button type="submit" class="btn-success">Ekle</button>
    </form>
}

FilmProjesi/Views/Home/Index.cshtml
@{
    var filmViewModel = ViewData["FilmViewModel"] as FilmViewModel;
}

<h1>Film Listesi</h1>
<ul>
    @foreach (var film in filmViewModel.Filmler)
    {
        <li>
            <a href="@Url.Action("FilmDetay", "Home", new { id = film.FilmID })">@film.FilmAd</a>
        </li>
    }
</ul>

@if(!User.Identity.IsAuthenticated)
{
    <form method="post" asp-controller="Film" asp-action="FilmEkle">
        <div class="input-group">
            <table class="table-bordered p-5">
                <tr>
                    <td>
                        <label>Film Adı:</label>
                    </td>
                    <td>
                        <input id="txtFilmAd" name="FilmAd" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Film Açıklaması:</label>
                    </td>
                    <td>
                        <textarea rows="4" cols="50" id="txtFilmAciklama" name="FilmAciklama"></textarea>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                        <button type="submit" class="btn-success">Film Ekle</button>
                    </td>
                </tr>
            </table>
        </div>
    </form>
}

FilmProjesi/Views/Home/YorumDuzenle.cshtml
@model Yorum
<form method="post" asp-controller="Home" asp-action="Duzenle">
    <input type="hidden" value="@Model.YorumID" id="id" name="id"/>
    <textarea rows="4" cols="50" id="txtNewYorum" name="NewYorum">@Model.YorumAciklama</textarea>
    <br/>
    <button type="submit">Düzenle</button>
</form>

FilmProjesi/Views/Home/Yorumlarim.cshtml
@model Dictionary<string, List<Yorum>>
<ul>
    @foreach (var key in Model.Keys)
    {
        <li>
            @key
            @foreach (var yorum in Model[key])
            {
                <ul>
                    <li>@yorum.YorumAciklama</li>
                    <li>@yorum.YorumTarihi</li>
                    <li><a href="@Url.Action("YorumSil","Home",new {id=yorum.YorumID})">Sil</a> <a href="@Url.Action("YorumDuzenle","Home",new {id=yorum.YorumID})">Düzenle</a></li>
                </ul> <br/>
            }
    </li>
}
</ul>

FilmProjesi/Views/Shared/_Layout.cshtml
@*@{
    var filmViewModel = ViewData["FilmViewModel"] as FilmViewModel;
}*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FilmProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FilmProjesi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid" style="background-color:aquamarine">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FilmProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                    </ul>
                    <ul>
                        @*<form id="filmForm" action="@Url.Action("FilmDetay", "Home")" method="post">
                            <select name="id">
                                @foreach (var film in ViewBag.FilmViewModel.Filmler)
                                {
                                    <option value="@film.FilmID">@film.FilmAd</option>
                                }
                            </select>
                            <button type="submit">Film Detayı</button>
                                </form>*@
                    </ul>
                    <ul>
                        <partial name="_LoginPartial" />
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FilmProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>